// <auto-generated />
using System;
using AireLineTicketSystem.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AireLineTicketSystem.Migrations
{
    [DbContext(typeof(AireLineTicketSystemContext))]
    [Migration("20210727222501_renameColumns")]
    partial class renameColumns
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AireLineTicketSystem.Entities.Airline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Airlines");
                });

            modelBuilder.Entity("AireLineTicketSystem.Entities.AirlineAirport", b =>
                {
                    b.Property<int?>("AirlineId")
                        .HasColumnType("int");

                    b.Property<int?>("AirportId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("AirlineId", "AirportId");

                    b.HasIndex("AirportId");

                    b.ToTable("AirlineAirport");
                });

            modelBuilder.Entity("AireLineTicketSystem.Entities.Airplane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AirlineId")
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.ToTable("Airplanes");
                });

            modelBuilder.Entity("AireLineTicketSystem.Entities.Airport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Airports");
                });

            modelBuilder.Entity("AireLineTicketSystem.Entities.BagPriceDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BagPriceMasterId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("PoundEnd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PoundStart")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BagPriceMasterId");

                    b.ToTable("BagPriceDetails");
                });

            modelBuilder.Entity("AireLineTicketSystem.Entities.BagPriceMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AirlineId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId")
                        .IsUnique();

                    b.ToTable("BagPriceMasters");
                });

            modelBuilder.Entity("AireLineTicketSystem.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "AF",
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = 2,
                            Code = "AX",
                            Name = "�land Islands"
                        },
                        new
                        {
                            Id = 3,
                            Code = "AL",
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 4,
                            Code = "DZ",
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 5,
                            Code = "AS",
                            Name = "American Samoa"
                        },
                        new
                        {
                            Id = 6,
                            Code = "AD",
                            Name = "AndorrA"
                        },
                        new
                        {
                            Id = 7,
                            Code = "AO",
                            Name = "Angola"
                        },
                        new
                        {
                            Id = 8,
                            Code = "AI",
                            Name = "Anguilla"
                        },
                        new
                        {
                            Id = 9,
                            Code = "AQ",
                            Name = "Antarctica"
                        },
                        new
                        {
                            Id = 10,
                            Code = "AG",
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = 11,
                            Code = "AR",
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 12,
                            Code = "AM",
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = 13,
                            Code = "AW",
                            Name = "Aruba"
                        },
                        new
                        {
                            Id = 14,
                            Code = "AU",
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 15,
                            Code = "AT",
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 16,
                            Code = "AZ",
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = 17,
                            Code = "BS",
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = 18,
                            Code = "BH",
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = 19,
                            Code = "BD",
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 20,
                            Code = "BB",
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = 21,
                            Code = "BY",
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = 22,
                            Code = "BE",
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 23,
                            Code = "BZ",
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 24,
                            Code = "BJ",
                            Name = "Benin"
                        },
                        new
                        {
                            Id = 25,
                            Code = "BM",
                            Name = "Bermuda"
                        },
                        new
                        {
                            Id = 26,
                            Code = "BT",
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = 27,
                            Code = "BO",
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = 28,
                            Code = "BA",
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = 29,
                            Code = "BW",
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = 30,
                            Code = "BV",
                            Name = "Bouvet Island"
                        },
                        new
                        {
                            Id = 31,
                            Code = "BR",
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 32,
                            Code = "IO",
                            Name = "British Indian Ocean Territory"
                        },
                        new
                        {
                            Id = 33,
                            Code = "BN",
                            Name = "Brunei Darussalam"
                        },
                        new
                        {
                            Id = 34,
                            Code = "BG",
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 35,
                            Code = "BF",
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = 36,
                            Code = "BI",
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = 37,
                            Code = "KH",
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = 38,
                            Code = "CM",
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = 39,
                            Code = "CA",
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 40,
                            Code = "CV",
                            Name = "Cape Verde"
                        },
                        new
                        {
                            Id = 41,
                            Code = "KY",
                            Name = "Cayman Islands"
                        },
                        new
                        {
                            Id = 42,
                            Code = "CF",
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = 43,
                            Code = "TD",
                            Name = "Chad"
                        },
                        new
                        {
                            Id = 44,
                            Code = "CL",
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 45,
                            Code = "CN",
                            Name = "China"
                        },
                        new
                        {
                            Id = 46,
                            Code = "CX",
                            Name = "Christmas Island"
                        },
                        new
                        {
                            Id = 47,
                            Code = "CC",
                            Name = "Cocos (Keeling) Islands"
                        },
                        new
                        {
                            Id = 48,
                            Code = "CO",
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 49,
                            Code = "KM",
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = 50,
                            Code = "CG",
                            Name = "Congo"
                        },
                        new
                        {
                            Id = 51,
                            Code = "CD",
                            Name = "Congo, The Democratic Republic of the"
                        },
                        new
                        {
                            Id = 52,
                            Code = "CK",
                            Name = "Cook Islands"
                        },
                        new
                        {
                            Id = 53,
                            Code = "CR",
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 54,
                            Code = "CI",
                            Name = "Cote D'Ivoire"
                        },
                        new
                        {
                            Id = 55,
                            Code = "HR",
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 56,
                            Code = "CU",
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 57,
                            Code = "CY",
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = 58,
                            Code = "CZ",
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = 59,
                            Code = "DK",
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 60,
                            Code = "DJ",
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = 61,
                            Code = "DM",
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = 62,
                            Code = "DO",
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = 63,
                            Code = "EC",
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 64,
                            Code = "EG",
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 65,
                            Code = "SV",
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 66,
                            Code = "GQ",
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = 67,
                            Code = "ER",
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = 68,
                            Code = "EE",
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 69,
                            Code = "ET",
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = 70,
                            Code = "FK",
                            Name = "Falkland Islands (Malvinas)"
                        },
                        new
                        {
                            Id = 71,
                            Code = "FO",
                            Name = "Faroe Islands"
                        },
                        new
                        {
                            Id = 72,
                            Code = "FJ",
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = 73,
                            Code = "FI",
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 74,
                            Code = "FR",
                            Name = "France"
                        },
                        new
                        {
                            Id = 75,
                            Code = "GF",
                            Name = "French Guiana"
                        },
                        new
                        {
                            Id = 76,
                            Code = "PF",
                            Name = "French Polynesia"
                        },
                        new
                        {
                            Id = 77,
                            Code = "TF",
                            Name = "French Southern Territories"
                        },
                        new
                        {
                            Id = 78,
                            Code = "GA",
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = 79,
                            Code = "GM",
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = 80,
                            Code = "GE",
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 81,
                            Code = "DE",
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 82,
                            Code = "GH",
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 83,
                            Code = "GI",
                            Name = "Gibraltar"
                        },
                        new
                        {
                            Id = 84,
                            Code = "GR",
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 85,
                            Code = "GL",
                            Name = "Greenland"
                        },
                        new
                        {
                            Id = 86,
                            Code = "GD",
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = 87,
                            Code = "GP",
                            Name = "Guadeloupe"
                        },
                        new
                        {
                            Id = 88,
                            Code = "GU",
                            Name = "Guam"
                        },
                        new
                        {
                            Id = 89,
                            Code = "GT",
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 90,
                            Code = "GG",
                            Name = "Guernsey"
                        },
                        new
                        {
                            Id = 91,
                            Code = "GN",
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = 92,
                            Code = "GW",
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = 93,
                            Code = "GY",
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = 94,
                            Code = "HT",
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = 95,
                            Code = "HM",
                            Name = "Heard Island and Mcdonald Islands"
                        },
                        new
                        {
                            Id = 96,
                            Code = "VA",
                            Name = "Holy See (Vatican City State)"
                        },
                        new
                        {
                            Id = 97,
                            Code = "HN",
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 98,
                            Code = "HK",
                            Name = "Hong Kong"
                        },
                        new
                        {
                            Id = 99,
                            Code = "HU",
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 100,
                            Code = "IS",
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = 101,
                            Code = "IN",
                            Name = "India"
                        },
                        new
                        {
                            Id = 102,
                            Code = "ID",
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 103,
                            Code = "IR",
                            Name = "Iran, Islamic Republic Of"
                        },
                        new
                        {
                            Id = 104,
                            Code = "IQ",
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = 105,
                            Code = "IE",
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = 106,
                            Code = "IM",
                            Name = "Isle of Man"
                        },
                        new
                        {
                            Id = 107,
                            Code = "IL",
                            Name = "Israel"
                        },
                        new
                        {
                            Id = 108,
                            Code = "IT",
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 109,
                            Code = "JM",
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 110,
                            Code = "JP",
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 111,
                            Code = "JE",
                            Name = "Jersey"
                        },
                        new
                        {
                            Id = 112,
                            Code = "JO",
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 113,
                            Code = "KZ",
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = 114,
                            Code = "KE",
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = 115,
                            Code = "KI",
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = 116,
                            Code = "KP",
                            Name = "Korea, Democratic People'S Republic of"
                        },
                        new
                        {
                            Id = 117,
                            Code = "KR",
                            Name = "Korea, Republic of"
                        },
                        new
                        {
                            Id = 118,
                            Code = "KW",
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 119,
                            Code = "KG",
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = 120,
                            Code = "LA",
                            Name = "Lao People'S Democratic Republic"
                        },
                        new
                        {
                            Id = 121,
                            Code = "LV",
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = 122,
                            Code = "LB",
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = 123,
                            Code = "LS",
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = 124,
                            Code = "LR",
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = 125,
                            Code = "LY",
                            Name = "Libyan Arab Jamahiriya"
                        },
                        new
                        {
                            Id = 126,
                            Code = "LI",
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 127,
                            Code = "LT",
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = 128,
                            Code = "LU",
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = 129,
                            Code = "MO",
                            Name = "Macao"
                        },
                        new
                        {
                            Id = 130,
                            Code = "MK",
                            Name = "Macedonia, The Former Yugoslav Republic of"
                        },
                        new
                        {
                            Id = 131,
                            Code = "MG",
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = 132,
                            Code = "MW",
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = 133,
                            Code = "MY",
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = 134,
                            Code = "MV",
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = 135,
                            Code = "ML",
                            Name = "Mali"
                        },
                        new
                        {
                            Id = 136,
                            Code = "MT",
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 137,
                            Code = "MH",
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = 138,
                            Code = "MQ",
                            Name = "Martinique"
                        },
                        new
                        {
                            Id = 139,
                            Code = "MR",
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = 140,
                            Code = "MU",
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = 141,
                            Code = "YT",
                            Name = "Mayotte"
                        },
                        new
                        {
                            Id = 142,
                            Code = "MX",
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 143,
                            Code = "FM",
                            Name = "Micronesia, Federated States of"
                        },
                        new
                        {
                            Id = 144,
                            Code = "MD",
                            Name = "Moldova, Republic of"
                        },
                        new
                        {
                            Id = 145,
                            Code = "MC",
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = 146,
                            Code = "MN",
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = 147,
                            Code = "MS",
                            Name = "Montserrat"
                        },
                        new
                        {
                            Id = 148,
                            Code = "MA",
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = 149,
                            Code = "MZ",
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = 150,
                            Code = "MM",
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = 151,
                            Code = "NA",
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = 152,
                            Code = "NR",
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = 153,
                            Code = "NP",
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 154,
                            Code = "NL",
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 155,
                            Code = "AN",
                            Name = "Netherlands Antilles"
                        },
                        new
                        {
                            Id = 156,
                            Code = "NC",
                            Name = "New Caledonia"
                        },
                        new
                        {
                            Id = 157,
                            Code = "NZ",
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 158,
                            Code = "NI",
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = 159,
                            Code = "NE",
                            Name = "Niger"
                        },
                        new
                        {
                            Id = 160,
                            Code = "NG",
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 161,
                            Code = "NU",
                            Name = "Niue"
                        },
                        new
                        {
                            Id = 162,
                            Code = "NF",
                            Name = "Norfolk Island"
                        },
                        new
                        {
                            Id = 163,
                            Code = "MP",
                            Name = "Northern Mariana Islands"
                        },
                        new
                        {
                            Id = 164,
                            Code = "NO",
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 165,
                            Code = "OM",
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 166,
                            Code = "PK",
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = 167,
                            Code = "PW",
                            Name = "Palau"
                        },
                        new
                        {
                            Id = 168,
                            Code = "PS",
                            Name = "Palestinian Territory, Occupied"
                        },
                        new
                        {
                            Id = 169,
                            Code = "PA",
                            Name = "Panama"
                        },
                        new
                        {
                            Id = 170,
                            Code = "PG",
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = 171,
                            Code = "PY",
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 172,
                            Code = "PE",
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 173,
                            Code = "PH",
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = 174,
                            Code = "PN",
                            Name = "Pitcairn"
                        },
                        new
                        {
                            Id = 175,
                            Code = "PL",
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 176,
                            Code = "PT",
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 177,
                            Code = "PR",
                            Name = "Puerto Rico"
                        },
                        new
                        {
                            Id = 178,
                            Code = "QA",
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 179,
                            Code = "RE",
                            Name = "Reunion"
                        },
                        new
                        {
                            Id = 180,
                            Code = "RO",
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 181,
                            Code = "RU",
                            Name = "Russian Federation"
                        },
                        new
                        {
                            Id = 182,
                            Code = "RW",
                            Name = "RWANDA"
                        },
                        new
                        {
                            Id = 183,
                            Code = "SH",
                            Name = "Saint Helena"
                        },
                        new
                        {
                            Id = 184,
                            Code = "KN",
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = 185,
                            Code = "LC",
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = 186,
                            Code = "PM",
                            Name = "Saint Pierre and Miquelon"
                        },
                        new
                        {
                            Id = 187,
                            Code = "VC",
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = 188,
                            Code = "WS",
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = 189,
                            Code = "SM",
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = 190,
                            Code = "ST",
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = 191,
                            Code = "SA",
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 192,
                            Code = "SN",
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 193,
                            Code = "CS",
                            Name = "Serbia and Montenegro"
                        },
                        new
                        {
                            Id = 194,
                            Code = "SC",
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = 195,
                            Code = "SL",
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = 196,
                            Code = "SG",
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 197,
                            Code = "SK",
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = 198,
                            Code = "SI",
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = 199,
                            Code = "SB",
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = 200,
                            Code = "SO",
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = 201,
                            Code = "ZA",
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 202,
                            Code = "GS",
                            Name = "South Georgia and the South Sandwich Islands"
                        },
                        new
                        {
                            Id = 203,
                            Code = "ES",
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 204,
                            Code = "LK",
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 205,
                            Code = "SD",
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = 206,
                            Code = "SR",
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = 207,
                            Code = "SJ",
                            Name = "Svalbard and Jan Mayen"
                        },
                        new
                        {
                            Id = 208,
                            Code = "SZ",
                            Name = "Swaziland"
                        },
                        new
                        {
                            Id = 209,
                            Code = "SE",
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 210,
                            Code = "CH",
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 211,
                            Code = "SY",
                            Name = "Syrian Arab Republic"
                        },
                        new
                        {
                            Id = 212,
                            Code = "TW",
                            Name = "Taiwan, Province of China"
                        },
                        new
                        {
                            Id = 213,
                            Code = "TJ",
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = 214,
                            Code = "TZ",
                            Name = "Tanzania, United Republic of"
                        },
                        new
                        {
                            Id = 215,
                            Code = "TH",
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = 216,
                            Code = "TL",
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            Id = 217,
                            Code = "TG",
                            Name = "Togo"
                        },
                        new
                        {
                            Id = 218,
                            Code = "TK",
                            Name = "Tokelau"
                        },
                        new
                        {
                            Id = 219,
                            Code = "TO",
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = 220,
                            Code = "TT",
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = 221,
                            Code = "TN",
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = 222,
                            Code = "TR",
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 223,
                            Code = "TM",
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = 224,
                            Code = "TC",
                            Name = "Turks and Caicos Islands"
                        },
                        new
                        {
                            Id = 225,
                            Code = "TV",
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = 226,
                            Code = "UG",
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = 227,
                            Code = "UA",
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 228,
                            Code = "AE",
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 229,
                            Code = "GB",
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 230,
                            Code = "US",
                            Name = "United States"
                        },
                        new
                        {
                            Id = 231,
                            Code = "UM",
                            Name = "United States Minor Outlying Islands"
                        },
                        new
                        {
                            Id = 232,
                            Code = "UY",
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 233,
                            Code = "UZ",
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = 234,
                            Code = "VU",
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = 235,
                            Code = "VE",
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = 236,
                            Code = "VN",
                            Name = "Viet Nam"
                        },
                        new
                        {
                            Id = 237,
                            Code = "VG",
                            Name = "Virgin Islands, British"
                        },
                        new
                        {
                            Id = 238,
                            Code = "VI",
                            Name = "Virgin Islands, U.S."
                        },
                        new
                        {
                            Id = 239,
                            Code = "WF",
                            Name = "Wallis and Futuna"
                        },
                        new
                        {
                            Id = 240,
                            Code = "EH",
                            Name = "Western Sahara"
                        },
                        new
                        {
                            Id = 241,
                            Code = "YE",
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 242,
                            Code = "ZM",
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = 243,
                            Code = "ZW",
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("AireLineTicketSystem.Entities.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AirlineId")
                        .HasColumnType("int");

                    b.Property<int?>("AirplaneId")
                        .HasColumnType("int");

                    b.Property<int?>("GateId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("PassengerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.HasIndex("AirplaneId");

                    b.HasIndex("GateId");

                    b.HasIndex("PassengerId");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("AireLineTicketSystem.Entities.FlightBagPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BagPriceDetailId")
                        .HasColumnType("int");

                    b.Property<int>("FlightScaleId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PassengerId")
                        .HasColumnType("int");

                    b.Property<decimal>("Pounds")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPaid")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BagPriceDetailId");

                    b.HasIndex("FlightScaleId");

                    b.HasIndex("PassengerId");

                    b.ToTable("FlightBagPayment");
                });

            modelBuilder.Entity("AireLineTicketSystem.Entities.FlightPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("EndTimePrice")
                        .HasColumnType("datetime2");

                    b.Property<int>("FlightScaleId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("StartTimePrice")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FlightScaleId");

                    b.ToTable("FlightPrices");
                });

            modelBuilder.Entity("AireLineTicketSystem.Entities.FlightScale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AirlineId")
                        .HasColumnType("int");

                    b.Property<int>("AirplaneId")
                        .HasColumnType("int");

                    b.Property<int>("AirportArrivalId")
                        .HasColumnType("int");

                    b.Property<int>("AirportDepartureId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DepartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("GateId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("MinPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TerminalId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalPaid")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.HasIndex("AirplaneId");

                    b.HasIndex("AirportArrivalId");

                    b.HasIndex("AirportDepartureId");

                    b.HasIndex("GateId");

                    b.HasIndex("TerminalId");

                    b.ToTable("FlightScale");
                });

            modelBuilder.Entity("AireLineTicketSystem.Entities.Gate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AirlineId")
                        .HasColumnType("int");

                    b.Property<int>("AirportId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.HasIndex("AirportId");

                    b.ToTable("Gates");
                });

            modelBuilder.Entity("AireLineTicketSystem.Entities.Passenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountryPassportId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PassportCode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CountryPassportId");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("AireLineTicketSystem.Entities.Terminal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AirlineId")
                        .HasColumnType("int");

                    b.Property<int>("AirportId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.HasIndex("AirportId");

                    b.ToTable("Terminals");
                });

            modelBuilder.Entity("AireLineTicketSystem.Entities.AirlineAirport", b =>
                {
                    b.HasOne("AireLineTicketSystem.Entities.Airline", "Airline")
                        .WithMany("AirlineAirport")
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AireLineTicketSystem.Entities.Airport", "Airport")
                        .WithMany("AirlineAirport")
                        .HasForeignKey("AirportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Airline");

                    b.Navigation("Airport");
                });

            modelBuilder.Entity("AireLineTicketSystem.Entities.Airplane", b =>
                {
                    b.HasOne("AireLineTicketSystem.Entities.Airline", "Airline")
                        .WithMany("Airplanes")
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Airline");
                });

            modelBuilder.Entity("AireLineTicketSystem.Entities.Airport", b =>
                {
                    b.HasOne("AireLineTicketSystem.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("AireLineTicketSystem.Entities.BagPriceDetail", b =>
                {
                    b.HasOne("AireLineTicketSystem.Entities.BagPriceMaster", "BagPriceMaster")
                        .WithMany()
                        .HasForeignKey("BagPriceMasterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BagPriceMaster");
                });

            modelBuilder.Entity("AireLineTicketSystem.Entities.BagPriceMaster", b =>
                {
                    b.HasOne("AireLineTicketSystem.Entities.Airline", "Airline")
                        .WithOne("BagPriceMaster")
                        .HasForeignKey("AireLineTicketSystem.Entities.BagPriceMaster", "AirlineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Airline");
                });

            modelBuilder.Entity("AireLineTicketSystem.Entities.Flight", b =>
                {
                    b.HasOne("AireLineTicketSystem.Entities.Airline", null)
                        .WithMany("Flights")
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AireLineTicketSystem.Entities.Airplane", null)
                        .WithMany("Flights")
                        .HasForeignKey("AirplaneId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AireLineTicketSystem.Entities.Gate", null)
                        .WithMany("Flights")
                        .HasForeignKey("GateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AireLineTicketSystem.Entities.Passenger", "Passenger")
                        .WithMany("Flights")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("AireLineTicketSystem.Entities.FlightBagPayment", b =>
                {
                    b.HasOne("AireLineTicketSystem.Entities.BagPriceDetail", "BagPriceDetail")
                        .WithMany()
                        .HasForeignKey("BagPriceDetailId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AireLineTicketSystem.Entities.FlightScale", "FlightScale")
                        .WithMany()
                        .HasForeignKey("FlightScaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AireLineTicketSystem.Entities.Passenger", "Passenger")
                        .WithMany()
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BagPriceDetail");

                    b.Navigation("FlightScale");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("AireLineTicketSystem.Entities.FlightPrice", b =>
                {
                    b.HasOne("AireLineTicketSystem.Entities.FlightScale", "FlightScale")
                        .WithMany("FlightPrices")
                        .HasForeignKey("FlightScaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FlightScale");
                });

            modelBuilder.Entity("AireLineTicketSystem.Entities.FlightScale", b =>
                {
                    b.HasOne("AireLineTicketSystem.Entities.Airline", "Airline")
                        .WithMany()
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AireLineTicketSystem.Entities.Airplane", "Airplane")
                        .WithMany()
                        .HasForeignKey("AirplaneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AireLineTicketSystem.Entities.Airport", "AirportArrival")
                        .WithMany()
                        .HasForeignKey("AirportArrivalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AireLineTicketSystem.Entities.Airport", "AirportDeparture")
                        .WithMany()
                        .HasForeignKey("AirportDepartureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AireLineTicketSystem.Entities.Gate", "Gate")
                        .WithMany()
                        .HasForeignKey("GateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AireLineTicketSystem.Entities.Terminal", "Terminal")
                        .WithMany()
                        .HasForeignKey("TerminalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Airline");

                    b.Navigation("Airplane");

                    b.Navigation("AirportArrival");

                    b.Navigation("AirportDeparture");

                    b.Navigation("Gate");

                    b.Navigation("Terminal");
                });

            modelBuilder.Entity("AireLineTicketSystem.Entities.Gate", b =>
                {
                    b.HasOne("AireLineTicketSystem.Entities.Airline", "Airline")
                        .WithMany("Gates")
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AireLineTicketSystem.Entities.Airport", "Airport")
                        .WithMany("Gates")
                        .HasForeignKey("AirportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Airline");

                    b.Navigation("Airport");
                });

            modelBuilder.Entity("AireLineTicketSystem.Entities.Passenger", b =>
                {
                    b.HasOne("AireLineTicketSystem.Entities.Country", "CountryPassport")
                        .WithMany()
                        .HasForeignKey("CountryPassportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CountryPassport");
                });

            modelBuilder.Entity("AireLineTicketSystem.Entities.Terminal", b =>
                {
                    b.HasOne("AireLineTicketSystem.Entities.Airline", "Airline")
                        .WithMany("Terminals")
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AireLineTicketSystem.Entities.Airport", "Airport")
                        .WithMany("Terminals")
                        .HasForeignKey("AirportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Airline");

                    b.Navigation("Airport");
                });

            modelBuilder.Entity("AireLineTicketSystem.Entities.Airline", b =>
                {
                    b.Navigation("AirlineAirport");

                    b.Navigation("Airplanes");

                    b.Navigation("BagPriceMaster");

                    b.Navigation("Flights");

                    b.Navigation("Gates");

                    b.Navigation("Terminals");
                });

            modelBuilder.Entity("AireLineTicketSystem.Entities.Airplane", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("AireLineTicketSystem.Entities.Airport", b =>
                {
                    b.Navigation("AirlineAirport");

                    b.Navigation("Gates");

                    b.Navigation("Terminals");
                });

            modelBuilder.Entity("AireLineTicketSystem.Entities.FlightScale", b =>
                {
                    b.Navigation("FlightPrices");
                });

            modelBuilder.Entity("AireLineTicketSystem.Entities.Gate", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("AireLineTicketSystem.Entities.Passenger", b =>
                {
                    b.Navigation("Flights");
                });
#pragma warning restore 612, 618
        }
    }
}
